### ISSUE TITLE
Segment uses Experiement Viewed instead of Experiment Play

### ISSUE THREAD

**Issue by SunnyGurnani** [pushtell/react-ab-test#15]
Thanks for this great library.

I checked Segment documentation and it uses Experiment Viewed.

https://segment.com/docs/spec/ab-testing/

**Comment by atu** [comment]
And I think Segment is using window.analytics and not window.segment.

**Comment by cloud-walker** [comment]
What about this issue?

**Comment by danieleleoni** [comment]
Hi guys, any news about this modification
We need to use this different name, but we really do not want to fork your project!

**Comment by wehriam** [comment]
Sorry, it's been a really busy time. I'll review these PRs within the next few days.

**Comment by peterpme** [comment]
@danieleleoni I think your fork fixes it! I think #19 fixes it anyway so I'll merge that in after testing it so you don't have to use a fork any longer :smile:

**Comment by peterpme** [comment]
Hey everyone,

I've merged in the changes!
