### ISSUE TITLE
Is this module still maintained?

### ISSUE THREAD

**Issue by rewop** [pushtell/react-ab-test#21]
We are suing `react-ab-test` but I noticed that important fixes like #17 are not being merged.

Also last commit in master was on 26th September 2016, and the last version published on npm was from 7 months ago.

I see an alternative: https://github.com/wanderio/react-ab-test. 

Should we stop using this repo?

**Comment by diondirza** [comment]
Seems we need to maintain it in our current fork instead of depending on this repo, seems pretty dead to me.

**Comment by peterpme** [comment]
Hey @rewop and @diondirza I'll be helping maintain this repo. Let me know what we can do to push this forward :)

Over the next couple of days I'll test and merge in the current PR's

**Comment by rewop** [comment]
@peterpme Good to hear. I think we should start by looking at the open PRs. https://github.com/pushtell/react-ab-test/pull/17 in particular made me realize that this module was quite outdated.

**Comment by jljorgenson18** [comment]
@peterpme NPM is still showing as 1.7 even though the latest is 1.9. Are there issues publishing new code at the moment?
