### ISSUE TITLE
Create Releases for last few versions

### ISSUE THREAD

**Issue by tysonnero** [pushtell/react-ab-test#28]
The latest version on npm is 1.7.0. Can you create releases for 1.7.1, 1.8.1 and 1.9.0?

**Comment by diondirza** [comment]
Yeah, can't find the package with the latest version.

**Comment by jljorgenson18** [comment]
Is there any update on this? With updates to React, this is becoming a big bottle neck in upgrading because of createClass.

**Comment by wehriam** [comment]
Resolved in 2.0.0 thanks to the PR.
