### ISSUE TITLE
Missing "Contribute" section

### ISSUE THREAD

**Issue by cloud-walker** [pushtell/react-ab-test#29]
Hi all, I need to use this package for now, but its not really updated as I've noticed.

So I want to contribute, to keep it updated and maybe add some features (like the segment identify for example, as my company need it). But I've noticed that no "how to contribute" section is present on the readme: for example I've discovered that if you `npm run build` It warns out that you need [doctoc](https://github.com/thlorenz/doctoc) to generate docs for example.

It would be great to add a section on the readme to leave some instructions for the future contributors.

I can try to open a PR about this, let me know if you think its a good idea and if you want to write something in particular in it (as I'm not really sure how the package really works!)

Thanks in advance!

**Comment by peterpme** [comment]
Hey @cloud-walker anything you can do to help bring this library up to speed would be great! I'm trying to do the same :)
