### ISSUE TITLE
npm test is broken

### ISSUE THREAD

**Issue by cloud-walker** [pushtell/react-ab-test#31]
if you try to `npm t` it throws an error:

<img width="712" alt="schermata 2017-05-22 alle 12 44 44" src="https://cloud.githubusercontent.com/assets/1144075/26304658/8c95e2fa-3eec-11e7-935a-4cc8d80a6036.png">

Thats because react test utils are deprecated in that form, I think we should upgrade to react 15.5 to solve this

**Comment by wehriam** [comment]
Resolved in 2.0.0 release.
