### ISSUE TITLE
react.createClass is deprecated

### ISSUE THREAD

**Issue by cloud-walker** [pushtell/react-ab-test#32]
From react 15.5 the createClass method is deprecated, we should be using esnext classes instead! Or `create-react-class` package.

<img width="1221" alt="schermata 2017-05-22 alle 12 46 55" src="https://cloud.githubusercontent.com/assets/1144075/26304723/c4395ebc-3eec-11e7-8bf0-84d84a8c1b27.png">

**Comment by peterpme** [comment]
Hey @cloud-walker thanks for the feedback! Do you mind opening a PR to fix this?

**Comment by cloud-walker** [comment]
Yes! For now I've just opened some issues as both memo and to notify my intentions 😉

**Comment by wehriam** [comment]
Resolved in 2.0.0 thanks to the PR.
