### ISSUE TITLE
Error message in PushtellEventEmitter.addExperimentVariant wrong

### ISSUE THREAD

**Issue by bigmac44** [pushtell/react-ab-test#5]
Line 183 of emitter.jsx

`const error = new Error("Expiriment “" + experimentName + "” added new variants after a variant was selected. Declare the variant names using emitter.addExpirimentVariants(expirimentName, variantNames).");`

I believe the message was probably meant to refer to the `defineVariants` method or `addExperimentVariant`

Experiment is also spelled wrong in both error messages of the method.

**Comment by wehriam** [comment]
Thanks for the report. I'll include this and #6 in a 1.5.0 release.
