### ISSUE TITLE
emitter.getActiveVariant() called without parameter

### ISSUE THREAD

**Issue by bigmac44** [pushtell/react-ab-test#6]
Line 48 of Experiment.jsx

`const activeValue = emitter.getActiveVariant();`

The `getActiveVariant` method takes an experiment name as a parameter.  Without supplying the experiment name, this method will never return anything.  I don't believe this is the intended behavior of the line.

**Comment by wehriam** [comment]
Thanks again for the report and review of the code. Please let me know if you encounter any additional issues.
